#!/usr/bin/env python3.2

import sys
import textwrap

import urbandict

def usage():
    print("Usage: %s <term>\n" % sys.argv[0])

if __name__ == "__main__":
    if len(sys.argv) != 2:
        usage()
        sys.exit(1)

    translations = urbandict.define(sys.argv[1])

    for index in range(len(translations)):
        print("%s. %s" % (index + 1, translations[index]['word']))
        print('\n'.join(textwrap.wrap(
                translations[index]['def'],
                initial_indent='  ',
                subsequent_indent='  ')
                )
            )

        if translations[index]['example'] != '':
            print("\n  Examples:\n")
            print('\n'.join(textwrap.wrap(
                    translations[index]['example'],
                    initial_indent='  * ',
                    subsequent_indent=' ' * 4)
                    )
                )
        print("\n")
